// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package assets

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// PossesUpdateAuthority is the `possesUpdateAuthority` instruction.
type PossesUpdateAuthority struct {
	AuthorityBump *uint8

	// [0] = [WRITE] initializer
	//
	// [1] = [WRITE] authority
	//
	// [2] = [] callerProgram
	//
	// [3] = [] mplMetadataProgram
	//
	// [4] = [WRITE] mint
	//
	// [5] = [WRITE] metadataAccount
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewPossesUpdateAuthorityInstructionBuilder creates a new `PossesUpdateAuthority` instruction builder.
func NewPossesUpdateAuthorityInstructionBuilder() *PossesUpdateAuthority {
	nd := &PossesUpdateAuthority{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetAuthorityBump sets the "authorityBump" parameter.
func (inst *PossesUpdateAuthority) SetAuthorityBump(authorityBump uint8) *PossesUpdateAuthority {
	inst.AuthorityBump = &authorityBump
	return inst
}

// SetInitializerAccount sets the "initializer" account.
func (inst *PossesUpdateAuthority) SetInitializerAccount(initializer ag_solanago.PublicKey) *PossesUpdateAuthority {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(initializer).WRITE()
	return inst
}

// GetInitializerAccount gets the "initializer" account.
func (inst *PossesUpdateAuthority) GetInitializerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *PossesUpdateAuthority) SetAuthorityAccount(authority ag_solanago.PublicKey) *PossesUpdateAuthority {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).WRITE()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *PossesUpdateAuthority) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetCallerProgramAccount sets the "callerProgram" account.
func (inst *PossesUpdateAuthority) SetCallerProgramAccount(callerProgram ag_solanago.PublicKey) *PossesUpdateAuthority {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(callerProgram)
	return inst
}

// GetCallerProgramAccount gets the "callerProgram" account.
func (inst *PossesUpdateAuthority) GetCallerProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetMplMetadataProgramAccount sets the "mplMetadataProgram" account.
func (inst *PossesUpdateAuthority) SetMplMetadataProgramAccount(mplMetadataProgram ag_solanago.PublicKey) *PossesUpdateAuthority {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(mplMetadataProgram)
	return inst
}

// GetMplMetadataProgramAccount gets the "mplMetadataProgram" account.
func (inst *PossesUpdateAuthority) GetMplMetadataProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetMintAccount sets the "mint" account.
func (inst *PossesUpdateAuthority) SetMintAccount(mint ag_solanago.PublicKey) *PossesUpdateAuthority {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(mint).WRITE()
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *PossesUpdateAuthority) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetMetadataAccountAccount sets the "metadataAccount" account.
func (inst *PossesUpdateAuthority) SetMetadataAccountAccount(metadataAccount ag_solanago.PublicKey) *PossesUpdateAuthority {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(metadataAccount).WRITE()
	return inst
}

// GetMetadataAccountAccount gets the "metadataAccount" account.
func (inst *PossesUpdateAuthority) GetMetadataAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst PossesUpdateAuthority) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_PossesUpdateAuthority,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst PossesUpdateAuthority) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *PossesUpdateAuthority) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.AuthorityBump == nil {
			return errors.New("AuthorityBump parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Initializer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.CallerProgram is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.MplMetadataProgram is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.MetadataAccount is not set")
		}
	}
	return nil
}

func (inst *PossesUpdateAuthority) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("PossesUpdateAuthority")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("AuthorityBump", *inst.AuthorityBump))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("       initializer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("         authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("     callerProgram", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("mplMetadataProgram", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("              mint", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("          metadata", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj PossesUpdateAuthority) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `AuthorityBump` param:
	err = encoder.Encode(obj.AuthorityBump)
	if err != nil {
		return err
	}
	return nil
}
func (obj *PossesUpdateAuthority) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `AuthorityBump`:
	err = decoder.Decode(&obj.AuthorityBump)
	if err != nil {
		return err
	}
	return nil
}

// NewPossesUpdateAuthorityInstruction declares a new PossesUpdateAuthority instruction with the provided parameters and accounts.
func NewPossesUpdateAuthorityInstruction(
	// Parameters:
	authorityBump uint8,
	// Accounts:
	initializer ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	callerProgram ag_solanago.PublicKey,
	mplMetadataProgram ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	metadataAccount ag_solanago.PublicKey) *PossesUpdateAuthority {
	return NewPossesUpdateAuthorityInstructionBuilder().
		SetAuthorityBump(authorityBump).
		SetInitializerAccount(initializer).
		SetAuthorityAccount(authority).
		SetCallerProgramAccount(callerProgram).
		SetMplMetadataProgramAccount(mplMetadataProgram).
		SetMintAccount(mint).
		SetMetadataAccountAccount(metadataAccount)
}
